
import React from 'react';
import { UtensilsCrossed, Scale, Factory } from 'lucide-react';
import { RecipePreset, ProductionScale } from './types';

export const PRESETS: RecipePreset[] = [
  { name: 'Napolitaine (AVPN)', nameEn: 'Neapolitan (AVPN)', hydration: 60, salt: 3, yeast: 0.1, oil: 0, sugar: 0 },
  { name: 'Napolitaine Contemporaine', nameEn: 'Contemporary Neapolitan', hydration: 70, salt: 2.8, yeast: 0.2, oil: 0, sugar: 0 },
  { name: 'Romaine', nameEn: 'Roman Style', hydration: 56, salt: 2.5, yeast: 0.2, oil: 3, sugar: 0 },
  { name: 'New York Style', nameEn: 'New York Style', hydration: 62, salt: 2, yeast: 0.4, oil: 2, sugar: 2 },
  { name: 'Detroit/Chicago', nameEn: 'Detroit/Chicago', hydration: 70, salt: 2.5, yeast: 0.5, oil: 4, sugar: 0 },
];

export const PRODUCTION_SCALES: ProductionScale[] = [
  {
    id: 'artisanal',
    name: 'Artisanal',
    nameEn: 'Artisanal',
    icon: <UtensilsCrossed className="w-4 h-4" />,
    pizzas: 4,
    weightPerBall: 250,
    description: 'Petite production',
    descriptionEn: 'Small batch',
    notes: 'Testez et affinez votre recette',
    notesEn: 'Test and refine your recipe'
  },
  {
    id: 'unit-a',
    name: 'Unité A',
    nameEn: 'Unit A',
    icon: <Scale className="w-4 h-4" />,
    pizzas: 45,
    weightPerBall: 250,
    description: 'Moyenne Échelle (~45 unités)',
    descriptionEn: 'Medium scale (~45 units)',
    notes: 'Vérifier la capacité du pétrin',
    notesEn: 'Check mixer capacity'
  },
  {
    id: 'unit-b',
    name: 'Unité B',
    nameEn: 'Unit B',
    icon: <Factory className="w-4 h-4" />,
    pizzas: 300,
    weightPerBall: 250,
    description: 'Grande Échelle (~300 unités)',
    descriptionEn: 'Large scale (~300 units)',
    notes: 'Vérifier la capacité du silo/pétrin',
    notesEn: 'Check silo/mixer capacity'
  }
];

export const TRANSLATIONS = {
  fr: {
    tagline: "Calculate. Bake. Master.",
    production: "1. PRODUCTION",
    formulation: "2. FORMULATION",
    roadmap: "3. FEUILLE DE ROUTE",
    loss_3: "Perte 3%",
    nb_pizzas: "Nombre de Pizzas",
    ball_weight: "Poids du Pâton (g)",
    total_mass: "Masse Totale Requise",
    hydration: "Hydratation",
    salt: "Sel",
    yeast: "Levure",
    yeast_dry: "Sèche",
    yeast_fresh: "Fraîche",
    oil: "Huile",
    sugar: "Sucre",
    advanced_options: "Ajuster Sel, Levure & Ingrédients",
    hide_advanced: "Masquer Options Avancées",
    thermal_control: "Contrôle Thermique",
    flour_temp: "Temp. Farine",
    ambient_temp: "Temp. Ambiante",
    ideal_water: "Temp. Eau Idéale",
    visualize: "Visualiser",
    export: "Exporter",
    copied: "Copié",
    flour_force: "Farine de Force",
    base_100: "Base 100%",
    water: "Eau",
    planning: "Planning Maturation",
    kneading: "Pétrissage & Pointage",
    shaping: "Mise en patons (Boulage)",
    baking: "Cuisson & Dégustation",
    fermentation_note: "Total Fermentation: {{hours}}h. Ajuste selon la force de ta farine (W).",
    shaping_note: "Laisse reposer à température ambiante",
    discuss: "Soutenir Pizzeo",
    support_note: "Vous aimez l'outil ? Aidez-moi à le maintenir gratuit et performant en m'offrant un café ou en proposant un partenariat.",
    ai_title: "Pizzeo AI",
    ai_tagline: "Intelligence Culinaire",
    ai_placeholder: "Pose une question sur la levée, la farine...",
    ai_thinking: "Pizzeo réfléchit...",
    ai_generating_img: "Génération de l'image en cours...",
    ai_welcome: "Prêt pour l'analyse...",
    auth_key_error: "Veuillez sélectionner votre clé API.",
    choose_key: "Choisir Clé",
    footer: "Pizzeo © {{year}} — Built for Masters",
    flour: "Farine",
    detailed_table: "Tableau Détaillé",
    calc_info: "Informations de Calcul",
    show: "Afficher",
    hide: "Masquer",
    ingredient: "Ingrédient",
    quantity: "Quantité",
    percentage: "Pourcentage",
    note: "Note"
  },
  en: {
    tagline: "Calculate. Bake. Master.",
    production: "1. PRODUCTION",
    formulation: "2. FORMULATION",
    roadmap: "3. ROADMAP",
    loss_3: "3% Loss",
    nb_pizzas: "Number of Pizzas",
    ball_weight: "Dough Ball Weight (g)",
    total_mass: "Total Mass Required",
    hydration: "Hydration",
    salt: "Salt",
    yeast: "Yeast",
    yeast_dry: "Dry",
    yeast_fresh: "Fresh",
    oil: "Oil",
    sugar: "Sugar",
    advanced_options: "Adjust Salt, Yeast & Ingredients",
    hide_advanced: "Hide Advanced Options",
    thermal_control: "Thermal Control",
    flour_temp: "Flour Temp",
    ambient_temp: "Ambient Temp",
    ideal_water: "Ideal Water Temp",
    visualize: "Visualize",
    export: "Export",
    copied: "Copied",
    flour_force: "Strong Flour",
    base_100: "100% Base",
    water: "Water",
    planning: "Maturation Planning",
    kneading: "Kneading & Bulk Fermentation",
    shaping: "Dough Ball Shaping",
    baking: "Baking & Tasting",
    fermentation_note: "Total Fermentation: {{hours}}h. Adjust based on flour strength (W).",
    shaping_note: "Let rest at room temperature",
    discuss: "Support Pizzeo",
    support_note: "Enjoying the tool? Help me keep it free and powerful by buying me a coffee or suggesting a partnership.",
    ai_title: "Pizzeo AI",
    ai_tagline: "Culinary Intelligence",
    ai_placeholder: "Ask a question about rising, flour...",
    ai_thinking: "Pizzeo is thinking...",
    ai_generating_img: "Generating image...",
    ai_welcome: "Ready for analysis...",
    auth_key_error: "Please select your API key.",
    choose_key: "Choose Key",
    footer: "Pizzeo © {{year}} — Built for Masters",
    flour: "Flour",
    detailed_table: "Detailed Table",
    calc_info: "Calculation Info",
    show: "Show",
    hide: "Hide",
    ingredient: "Ingredient",
    quantity: "Quantity",
    percentage: "Percentage",
    note: "Note"
  }
};
